<?php

/**
 * @file
 * Module for creating the A11Y Paragraphs Tabs paragraph component.
 */

/**
 * Implements hook_theme().
 *
 * Call the base hook from Paragraphs to allow preprocess hooks to work.
 */
function a11y_paragraphs_tabs_theme(): array {
  return [
    'paragraph__a11y_paragraphs_tabs_wrapper' => [
      'render element' => 'element',
      'template' => 'paragraph--a11y-paragraphs-tabs-wrapper',
      'base hook' => 'paragraph',
    ],

    'field__field_a11y_para_tabs_tabs_panel' => [
      'render element' => 'content',
      'template' => 'field--field-a11y-para-tabs-tabs-panel',
      'base hook' => 'field',
    ],

    'field__field_a11y_para_tabs_tab_title' => [
      'render_element' => 'content',
      'base_hook' => 'field',
      'template' => 'field--field-a11y-para-tabs-tab-title',
    ],

  ];
}

/**
 * Implements hook_help().
 */
function a11y_paragraphs_tabs_help($route_name) {
  switch ($route_name) {
    case 'help.page.a11y_paragraphs_tabs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A11Y Paragraphs Tabs gives the user the ability to easily add tabs via paragraphs to their content that complies to Accessibility (A11Y) standards. On Desktop it shows Tabs and on mobile it displays as an accordion. For more information, see the <a href=":a11y_paragraphs_tabs">A11Y Paragraphs Tabs documentation on Drupal.org.</a>.', [
        ':a11y_paragraphs_tabs' => 'https://www.drupal.org/docs/8/modules/a11y-paragraphs-tabs',
      ]) . '</p>';
      return $output;

    case 'dblog.overview':
      return '<p>' . t('A11Y Paragraphs Tabs gives the user the ability to easily add tabs via paragraphs to their content that complies to Accessibility (A11Y) standards.') . '</p>';
  }
}

/**
 * Implements HOOK_preprocess_paragraph().
 */
function a11y_paragraphs_tabs_preprocess_paragraph(array &$vars): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $vars['paragraph'];
  switch ($paragraph->bundle()) {
    case 'a11y_paragraphs_tabs_wrapper':
      $vars['titles'] = [];
      /** @var \Drupal\paragraphs\Entity\Paragraph $tab */
      foreach ($paragraph->get('field_a11y_para_tabs_tabs_panel')->referencedEntities() as $tab) {
        if ($field = $tab->get('field_a11y_para_tabs_tab_title')) {
          $vars['titles'][] = $field->view();
        }
      }
  }
}
